### ISSUE TITLE
Deployed backend keeps going down every night

### ISSUE THREAD

**Issue by jsun1** [CandlePlatforms/quickstart#5]
Opening an issue to investigate why the deployed backend at api.maltafinance.org has been going down every night. I'm finding that I need to restart it daily, and this has been happening since the first time I deployed the backend in `/home/candle/quickstart/node`

cc @kiranmuddam @samisbakedham 

For reference, the way I start the backend running is by going to https://console.cloud.google.com/compute/instances?project=malta-backend

Then clicking "SSH" on instance-1, and then navigating to `/home/candle/quickstart/node` in the Terminal and running `node index.js`

**Comment by Laphatize** [comment]
I suggest for now as a temporary fix we could use something like pm2.io to auto redeploy the server upon crashing.
https://pm2.keymetrics.io/

**Comment by jsun1** [comment]
Awesome thanks! I re-deployed the server using `pm2 start index.js --name "CNDLE"` just now.

**Comment by samisbakedham** [comment]
> Opening an issue to investigate why the deployed backend at api.maltafinance.org has been going down every night. I'm finding that I need to restart it daily, and this has been happening since the first time I deployed the backend in `/home/candle/quickstart/node`
> 
> cc @kiranmuddam @samisbakedham
> 
> For reference, the way I start the backend running is by going to https://console.cloud.google.com/compute/instances?project=malta-backend
> 
> Then clicking "SSH" on instance-1, and then navigating to `/home/candle/quickstart/node` in the Terminal and running `node index.js`

Just start it in a tmux screen then detach

**Comment by jsun1** [comment]
Great, thanks for the responses - closing this issue now.
